run:
  timeout: 3m

linters-settings:
  errcheck:
    exclude-functions:
      - (*github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.ResourceData).Set
      - crypto/rand.Read

linters:
  enable:
    - errcheck
    - staticcheck
    - unused

issues:
  exclude-rules:
    - linters:
        - errcheck
      text: "DeleteKPI|AttachNotificationChannel"
    - linters:
        - staticcheck
      text: "SA1019.*plugin.Debug"
    - linters:
        - staticcheck
      text: "SA9003"
    - linters:
        - unused
      path: resource_notification_channel_attachment.go
